

DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS feed;
DROP TABLE IF EXISTS feedHistory;
DROP TABLE IF EXISTS form;
DROP TABLE IF EXISTS item;

CREATE TABLE member
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  fbLink VARCHAR(255) NOT NULL,
  blogLink VARCHAR(255)	NOT NULL
);

CREATE TABLE feed
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  memberId BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255)	NOT NULL,
  version INT
);

CREATE TABLE feedHistory
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  createdDate date,
  contents VARCHAR(255)	NOT NULL,
  feedId BIGINT NOT NULL
);

CREATE TABLE form
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  memberId BIGINT NOT NULL,
  createdDate date,
  updatedDate date
);

CREATE TABLE item
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  formId BIGINT NOT NULL,
  content VARCHAR(255)	NOT NULL,
  confirm BOOLEAN DEFAULT FALSE
);