INSERT INTO POKE_BALL( ID, NAME, BONUS_MULTIPLIER ) VALUES ( 1, '마스터볼', 255 );
INSERT INTO POKE_BALL( ID, NAME, BONUS_MULTIPLIER ) VALUES ( 2, '하이퍼볼', 2.0 );
INSERT INTO POKE_BALL( ID, NAME, BONUS_MULTIPLIER ) VALUES ( 3, '수퍼볼', 1.5 );
INSERT INTO POKE_BALL( ID, NAME, BONUS_MULTIPLIER ) VALUES ( 4, '몬스터볼', 1.0 );