language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

script:
  - "npm run win_start"

notifications:
  email:
    recipients:
      - brainbackdoor@gmail.com