DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS feed;
DROP TABLE IF EXISTS feedHistory;
CREATE TABLE member
(
  idx BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  fbLink VARCHAR(255) NOT NULL,
  blogLink VARCHAR(255)	NOT NULL
);

CREATE TABLE feed
(
  idx BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  memberIdx BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255)	NOT NULL,
  version INT
);

CREATE TABLE feedHistory
(
  idx BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  createdDate date,
  contents VARCHAR(255)	NOT NULL,
  feedIdx BIGINT NOT NULL
);